imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
    # app:
    #     title: DPO's 3D Repository

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_title: DPO's 3D Repository
        admin_email: '%mailer_user%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        options:
          # PDO::MYSQL_ATTR_INIT_COMMAND
          1002: "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"
        #unix_socket: /Applications/DevDesktop/mysql/data/mysql.sock
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
    router:
        annotations: false

# DebugBundle Configuration
# http://symfony.com/doc/3.4/reference/configuration/debug.html
# By default, the dumps are shown in the toolbar. Since this is not always possible 
# (e.g. when working on a JSON API), you can have an alternate output destination for dumps.
# Typically, you would set this to php://stderr
#debug:
#    dump_destination: php://stderr

# FOSUserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# FR3DLdapBundle Configuration
fr3d_ldap:
    driver:
        host: '%si_ldap_host%'
        username: '%si_ldap_username%'
        password: '%si_ldap_password%'
        port: 636
        useSsl: true
        optReferrals: true
        accountCanonicalForm: 3
        bindRequiresDn: true
        accountDomainName: '%si_ldap_account_domain_name%'
        accountDomainNameShort: US
    user:
        baseDn: '%si_ldap_base_dn%'
        usernameAttribute: sAMAccountName
        filter: (&(ObjectClass=person))
        attributes:
            - { ldap_attr: samaccountname,  user_method: setUsername }
            - { ldap_attr: mail,  user_method: setEmail }
    # driver:
    #     host: ldap.forumsys.com
    # user:
    #     baseDn: dc=example,dc=com
    #     attributes:
    #         - { ldap_attr: uid,  user_method: setUsername }
    #         - { ldap_attr: mail,  user_method: setEmail }
    #     filter: (&(ObjectClass=person))

# OneupUploaderBundle Configuration
oneup_uploader:
    mappings:
        repository:
            frontend: dropzone
            # If you want to use your own path, for example /data/uploads
            # storage:
            #     directory: "%kernel.root_dir%/../data/uploads/"
            # namer: oneup_uploader.namer.uniqid
            namer: app.file_namer

# OneupFlysystemBundle Configuration
oneup_flysystem:
    adapters:
        assets_adapter:
            webdav:
                client: app.sabredav_client

    filesystems:
        assets:
            adapter: assets_adapter
            cache: ~
            alias: ~
            mount: ~